# -*- coding: utf-8 -*-
"""Global Cybersecurity Threat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YK0Xiqtde9pRHiZP1H4jMnfFB98BHRkj
"""

# Cybersecurity Risk Assessment for Public Policy

"""Although the dataset is based on real-world cybersecurity themes and sourced from Kaggle, its balanced distributions and simplified structure may limit the generalizability of the findings to actual global cybersecurity incident patterns.

"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score)

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from scipy import stats
from scipy.stats import pearsonr
from scipy.stats import f_oneway
from scipy.stats import chi2_contingency
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

## Dataset Description
df=pd.read_csv("Global_Cybersecurity_Threats_2015-2024.csv")
df.head()
df.shape
df.columns
df.info()
df.describe()

## Check Missing values
df.isnull().sum()

## Check for Duplicate Rows
df.duplicated().sum()

## Check unique values in Categorical Columns
df['Attack Type'].unique()
df['Attack Type'].value_counts()

df['Country'].value_counts()

df['Target Industry'].value_counts()

df['Security Vulnerability Type'].value_counts()

df['Defense Mechanism Used'].value_counts()

## Initial Observations
# Dataset contains 3000 rows and 10 columns. It has 3000 reported cyber crime incidents.
# It contains six categorical variables and four numerical variables.
# There are no missing values in the dataset.
# Attack Type, Target Industry, Country, Security Vulnerability Type and defense Mechanism used - contain several distinct categories.
# There are no duplicate observation in the dataset.

## Data Cleaning
df.dtypes

## Check for outliers
df.boxplot(column="Financial Loss (in Million $)")
plt.show()

df.boxplot(column="Incident Resolution Time (in Hours)" )
plt.show()

from numpy._core.fromnumeric import sort
## Exploratory Data Analysis (EDA)
# Research Question 1
# Which countries experience the greatest financial losses from cyber attacks?
country_loss = (df.groupby("Country")["Financial Loss (in Million $)"]
.mean()
.sort_values(ascending=False)
)
country_loss

country_loss.plot(kind="bar", figsize=(6,6))
plt.xlabel("Country")
plt.ylabel("Average Financial Loss (in Million $)")
plt.title("Average Financial Loss by Country")
plt.grid(True)
plt.show()

# Research Question 2
# Which industries experience the greatest financial losses?
industry_loss = (df.groupby("Target Industry")["Financial Loss (in Million $)"]
.mean()
.sort_values(ascending=False)
)
industry_loss

industry_loss.plot(kind="bar", figsize=(10,6))

plt.title("Average Financial Loss by Industry")
plt.xlabel("Industry")
plt.ylabel("Average Financial Loss (Million $)")
plt.grid(True)
plt.show()

# Research Question 3:
# Which attack types result in the greatest financial losses?
attack_loss = (
    df.groupby("Attack Type")["Financial Loss (in Million $)"]
      .mean()
      .sort_values(ascending=False))
attack_loss
attack_loss.plot(kind="bar", figsize=(6,6))
plt.title("Average Financial Loss by Attack Type")
plt.xlabel("Attack Type")
plt.ylabel("Average Financial Loss (Million $)")
plt.grid(True)
plt.show()

# Research Question 4:
# How has financial loss changed over time?
year_loss = (
    df.groupby("Year")["Financial Loss (in Million $)"]
      .mean())
year_loss.plot(marker="o", figsize=(6,6))
plt.title("Average Financial Loss by Year")
plt.xlabel("Year")
plt.ylabel("Average Financial Loss (Million $)")
plt.grid(True)
plt.show()

# Research Question 5:
# Does a longer incident resolution time tend to correspond to higher financial losses?
plt.figure(figsize=(8,6))
plt.scatter(
    df["Incident Resolution Time (in Hours)"],
    df["Financial Loss (in Million $)"],
    alpha=0.6, s=10)

plt.xlabel("Incident Resolution Time (in Hours)")
plt.ylabel("Financial Loss (in Million $)")
plt.title("Incident Resolution Time vs. Financial Loss")
plt.grid(True)
plt.show()

resolution_loss = (df.groupby("Incident Resolution Time (in Hours)") ["Financial Loss (in Million $)"]
.mean()
)
resolution_loss.plot(figsize=(10,6), marker="o")
plt.title("Average Financial Loss by Incident Resolution Time")
plt.xlabel("Incident Resolution Time (Hours)")
plt.ylabel("Average Financial Loss (Million $)")
plt.grid(True)
plt.show()

# we need to find out whether incident resolution time is associated with financial loss?
# Observations:
# - Financial loss and Resolution Time are numeric variables.
# - So pearson correlation coefficient is appropriate.

# pearson correlation
correlation, p_value = pearsonr(df["Incident Resolution Time (in Hours)"], df["Financial Loss (in Million $)"])
print("Correlation:", correlation)
print("P-value:", p_value)

"""Since the correlation value is in negative, there is no significant relationship between resolution time and finanacial loss.
The value of p value is also 0.48 which is significantly greater than the statistical threshold of 0.05.
This suggests that simply resolving incidents more quickly is not, by itself, associated with lower financial losses.
"""

# ANOVA: Do industries experience different average financial losses?
industry_groups = []

for industry in df["Target Industry"].unique():
    industry_groups.append(
        df[df["Target Industry"] == industry]["Financial Loss (in Million $)"]
    )

f_stat, p_value = f_oneway(*industry_groups)

print("F-statistic:", f_stat)
print("P-value:", p_value)

"""Here the P-value > 0.05; that is not statistically significant. Thus there is no sufficient evidence that average losses differ across industries.
Based on this dataset, no industry stands out as having consistently higher average financial losses.
"""

# Chi Square Test: Is the Attack type associated with Security Vulnerability Type?
contingency_table= pd.crosstab(df["Attack Type"], df["Security Vulnerability Type"])
contingency_table

chi2, p_value, dof, expected = chi2_contingency(contingency_table)

print("Chi-square:", chi2)
print("P-value:", p_value)

"""The P value > 0.05, so the association is not statistically significant. Therefore, there is insufficient evidence to conclude that attack type and vulnerability type are associated in this dataset."""

# Machine Learning
# How much does each variable contribute to financial loss while controlling for the others?
# Dependent Variable is Financial Loss (in Milloin $) - y variable

"""Independent Variable (Predictors) are Country
Year
Attack Type
Target Industry
Number of Affected Users
Attack Source
Security Vulnerability Type
Defense Mechanism Used
Incident Resolution Time  - x variable.
"""

df_encoded = pd.get_dummies(
    df,
    columns=["Country", "Attack Type", "Target Industry", "Attack Source", "Security Vulnerability Type", "Defense Mechanism Used"],
drop_first=True
)
x = df_encoded.drop("Financial Loss (in Million $)", axis=1)
y = df_encoded["Financial Loss (in Million $)"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(x_train, y_train)

predictions = model.predict(x_test)

m = mean_squared_error(y_test, predictions)
r = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)
print("Mean Squared Error:", m)
print("Root Mean Squared Error:", r)
print("R-squared:", r2)

coefficients = pd.DataFrame({
    "Variable": x.columns,
    "Coefficient": model.coef_
})

coefficients.sort_values(
    by="Coefficient",
    ascending=False
)

"""The model failed to predict financial losses.The R squared score was zero (-0.006). The current data is missing the key pieces. thus this needs different variables to explain the losses."""

tree_model = DecisionTreeRegressor(
    random_state=42
)
tree_model.fit(x_train, y_train)

tree_predictions = tree_model.predict(x_test)

tree_mae = mean_absolute_error( y_test, tree_predictions)
tree_rmse = np.sqrt( mean_squared_error(y_test, tree_predictions))
tree_r2 = r2_score( y_test, tree_predictions)
print("Mean Absolute Error:", tree_mae)
print("Root Mean Squared Error:", tree_rmse)
print("R-squared:", tree_r2)

rf_model = RandomForestRegressor(
    n_estimators=100,
    random_state=42)
rf_model.fit( x_train, y_train)

rf_predictions = rf_model.predict(x_test)

rf_mae = mean_absolute_error(y_test, rf_predictions)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_predictions))
rf_r2 = r2_score(y_test, rf_predictions)
print("Mean Absolute Error:", rf_mae)
print("Root Mean Squared Error:", rf_rmse)
print("R-squared:", rf_r2)

results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest"],
    "MAE": [
        m,
        tree_mae,
        rf_mae],
    "RMSE": [
        r,
        tree_rmse,
        rf_rmse],
    "R²": [
        r2,
        tree_r2,
        rf_r2]
})
results

importance = pd.DataFrame({
    "Feature": x_train.columns,
    "Importance": rf_model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(10)

top10 = importance.head(10)
plt.figure(figsize=(10,6))
plt.barh(
    top10["Feature"],
    top10["Importance"])
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 10 Important Features")
plt.gca().invert_yaxis()
plt.show()

"""Three different models (Linear Regression, Decision Tree, and Random Forest) were tested to predict financial losses from cybersecurity incidents.

None of the models worked well. They all performed poorly and couldn't accurately predict the losses.The

Linear Regression technically did the "best," but its score was still negative (-0.006$).
A negative score means the models were so inaccurate that you would get better results by simply guessing the average financial loss every time.
Thus, The current data and variables used in the study simply do not contain enough information to explain or predict financial losses.
"""

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[[
    "Loss_Scaled",
    "Users_Scaled",
    "Resolution_Scaled"
]] = scaler.fit_transform(
    df[[
        "Financial Loss (in Million $)",
        "Number of Affected Users",
        "Incident Resolution Time (in Hours)"
    ]])
df["Risk Score"] = (
    df["Loss_Scaled"] +
    df["Users_Scaled"] +
    df["Resolution_Scaled"]
) / 3

"""Cybersecurity Risk Index:
Risk Score = Normalized Financial Loss + Normalized Affected users + Normalized Resolution Time / 3.
"""

country_risk = (
    df.groupby("Country")["Risk Score"]
      .mean()
      .sort_values(ascending=False))
country_risk

# the scores are almost very near, so no country stands out riskier than the other countries in this daataset.

plt.figure(figsize=(6,6))
country_risk.plot(kind="bar")
plt.title("Average Cybersecurity Risk Score by Country")
plt.xlabel("Country")
plt.ylabel("Average Risk Score")
plt.grid(True)
plt.show()

"""Brazil recorded the highest average cybersecurity risk score, while India recorded the lowest. However, the differences between countries were relatively small, suggesting a fairly uniform distribution of cyber risk across the countries represented in the dataset."""

industry_risk = (
    df.groupby("Target Industry")["Risk Score"]
      .mean()
      .sort_values(ascending=False))
industry_risk

# The sectors are also in the same range with only minute dissimilarities. The difference between the highest and the lowest is only 0.019.

"""Government and IT appear to have slightly higher overall risk according to the constructed index.
However,the differences are modest.
The policy recommendations should focus on strengthening cybersecurity across all sectors, rather than concentrating exclusively on one industry.
"""

plt.figure(figsize=(6,6))
industry_risk.plot(kind="bar")
plt.title("Average Cybersecurity Risk Score by Country")
plt.xlabel("Country")
plt.ylabel("Average Risk Score")
plt.grid(True)
plt.show()

def classify_risk(score):
    if score >= 0.70:
        return "High"
    elif score >= 0.40:
        return "Medium"
    else:
        return "Low"
df["Risk Level"] = df["Risk Score"].apply(classify_risk)
df["Risk Level"].value_counts()

"""Most incidents fall into the Medium Risk category. Only 12% are classified as High Risk. Extremely severe incidents are relatively uncommon."""

risk_counts = df["Risk Level"].value_counts()
plt.figure(figsize=(6,6))
plt.pie(
    risk_counts,
    labels=risk_counts.index,
    autopct="%1.1f%%",
    startangle=90)
plt.title("Distribution of Cybersecurity Risk Levels")
plt.show()

"""Policy Implications: Based on this project:

1. Since no country or industry is dramatically different from the others, governments shouls strengthen cybersecurity capacity acorss sectors rather than focusing on a single target.
2. Although response time was not statistically significant in this dataset for financial loss, faster detection and mitigation remain a good cybersecurity practice.
3. Because Government and IT received the highest composite risk scores, they could be prioritized for planning and regular security assesssments.
4.
"""











